import json
import os


NUM_TOKENS = 250

KNOWN_IPFS_1 = "QmRN8VdKcxPaFNXQAJZUSwc35RERKjsFsYtM8pC1M4kpCg" # 1 - 70
KNOWN_IPFS_2 = "QmaKe9RQpV7UC1xC6WZgbVV1nRD41UR4s71ny9HB5SLYRv" # 71 - 140
KNOWN_IPFS_3 = "QmeJ1pzwNQ9qd79U1CKsm8A9f6xVdz5fa9AdJwshkASwRW" # 141 - 210
KNOWN_IPFS_4 = "QmahkqMWbTxkrcNjt15C9HHz1MckXAvCXvT4b2WBPPoCS4" # 211 - 250

MISC_IPFS = "QmbtCZDTv9mWGv158ThfCW93Mxy8c7MnjDqfjUJeyzBBCF"

BASE_PATH = "../assets/metadata"
UNKNOWN_PATH = f"{BASE_PATH}/unknown"
KNOWN_PATH = f"{BASE_PATH}/known"
MISC_PATH = f"{BASE_PATH}/misc"


def generate_unknown_metadata() -> None:
    _create_dir(UNKNOWN_PATH)

    for i in range(NUM_TOKENS):
        id = i+1
        with open(f'{UNKNOWN_PATH}/{id}.json', 'w+') as outfile:
            json.dump(unknown_template(id), outfile)

def generate_known_metadata() -> None:
    _create_dir(KNOWN_PATH)

    for i in range(NUM_TOKENS):
        id = i+1
        with open(f'{KNOWN_PATH}/{id}.json', 'w+') as outfile:
            json.dump(known_template(id), outfile)

def generate_misc_metadata() -> None:
    _create_dir(MISC_PATH)

    misc_files = [
        ["collection", collection_template],
        ["factory", factory_template]
    ]

    for f in misc_files:
        with open(f'{MISC_PATH}/{f[0]}.json', 'w+') as outfile:
            json.dump(f[1](), outfile)

def _create_dir(path: str):
    try:
        os.mkdir(path)
    except FileExistsError:
        pass

def unknown_template(id: int) -> dict:
    return {
        "name": f"{UNKNOWN_NAME[id-1]}",
        "description": "NostaLex: A body of work by artist Coinslot with 250 hand-drawn Lex the Copy Cat inspired by childhood memories. Welcome to the club.\n\nGoodluck on your slot spin.",
        "image": f"ipfs://{MISC_IPFS}/unknown.jpg",
    }

def known_template(id: int) -> dict:
    if id >= 1 and id <= 70:
        url = KNOWN_IPFS_1
    elif id >= 71 and id <= 140:
        url = KNOWN_IPFS_2
    elif id >= 141 and id <= 210:
        url = KNOWN_IPFS_3
    elif id >= 211 and id <= 250:
        url = KNOWN_IPFS_4

    return {
        "name": f"{KNOWN_NAME[id-1]}",
        "description": "Coinslot 1/1 from the NostaLex Collection.\n\nNostaLex: A body of work by the artist Coinslot that consist of 250 hand-drawn 1/1 pieces of his most recognized character, Lex the Copy Cat, inspired by childhood memories and memorabilia. Welcome to the Slot Gang fam.\n\nAll rights pertaining to the artwork and IP belongs to Coinslot Worldwide Inc.",
        "image": f"ipfs://{url}/{id}.jpg",
    }

def collection_template() -> dict:
    return {
        "name": "NostaLex",
        "description": "NostaLex is a collection of 250 1/1 hand-drawn pieces made by artist Coinslot. The body of work is based off Coinslot’s main character Lex the Copy Cat and is inspired by cartoons, movie characters from the early 90s, and memories of watching TV after school.\n\nThe goal of this project is to share the body of work and to reinvest into bigger art projects, the overall Coinslot brand, and give back as much utility such as physical goods, discounts, and events to the Coinslot community.\n\nI invite you to take a journey with me into my childhood and hopefully yours as well. I hope you enjoy this collection as much as I enjoyed creating it.\n\n\- Coinslot",
        "image": f"ipfs://{MISC_IPFS}/collection.jpg",
        "seller_fee_basis_points": 800,
        "fee_recipient": "0xeCf607e6Ad6Ec6F9B895E818F95Bd3bBdA3152e3"
    }
    

def factory_template() -> dict:
    return {
        "name": "NostaLex Mint",
        "description": "NostaLex is the artist Coinslot's first NFT collection consisting of 250 1/1 hand-drawn pieces. You can mint your NostaLex NFT here.",
        "image": f"ipfs://{MISC_IPFS}/factory.jpg"
    }

UNKNOWN_NAME = [
    "Lex #31",
    "Lex #44",
    "Lex #172",
    "Lex #67",
    "Lex #110",
    "Lex #186",
    "Lex #111",
    "Lex #75",
    "Lex #204",
    "Lex #206",
    "Lex #108",
    "Lex #51",
    "Lex #60",
    "Lex #226",
    "Lex #122",
    "Lex #143",
    "Lex #85",
    "Lex #156",
    "Lex #239",
    "Lex #195",
    "Lex #246",
    "Lex #249",
    "Lex #188",
    "Lex #119",
    "Lex #232",
    "Lex #20",
    "Lex #58",
    "Lex #116",
    "Lex #19",
    "Lex #194",
    "Lex #72",
    "Lex #33",
    "Lex #210",
    "Lex #173",
    "Lex #202",
    "Lex #78",
    "Lex #182",
    "Lex #187",
    "Lex #225",
    "Lex #134",
    "Lex #215",
    "Lex #245",
    "Lex #237",
    "Lex #241",
    "Lex #218",
    "Lex #73",
    "Lex #166",
    "Lex #64",
    "Lex #74",
    "Lex #91",
    "Lex #70",
    "Lex #224",
    "Lex #247",
    "Lex #178",
    "Lex #154",
    "Lex #221",
    "Lex #68",
    "Lex #17",
    "Lex #185",
    "Lex #184",
    "Lex #196",
    "Lex #177",
    "Lex #23",
    "Lex #248",
    "Lex #3",
    "Lex #39",
    "Lex #152",
    "Lex #158",
    "Lex #83",
    "Lex #4",
    "Lex #8",
    "Lex #231",
    "Lex #87",
    "Lex #104",
    "Lex #41",
    "Lex #24",
    "Lex #171",
    "Lex #161",
    "Lex #250",
    "Lex #46",
    "Lex #82",
    "Lex #65",
    "Lex #207",
    "Lex #29",
    "Lex #9",
    "Lex #164",
    "Lex #79",
    "Lex #179",
    "Lex #213",
    "Lex #99",
    "Lex #96",
    "Lex #244",
    "Lex #45",
    "Lex #117",
    "Lex #155",
    "Lex #56",
    "Lex #160",
    "Lex #57",
    "Lex #208",
    "Lex #214",
    "Lex #130",
    "Lex #123",
    "Lex #27",
    "Lex #107",
    "Lex #80",
    "Lex #14",
    "Lex #144",
    "Lex #169",
    "Lex #103",
    "Lex #28",
    "Lex #13",
    "Lex #142",
    "Lex #197",
    "Lex #201",
    "Lex #42",
    "Lex #238",
    "Lex #175",
    "Lex #55",
    "Lex #219",
    "Lex #121",
    "Lex #128",
    "Lex #146",
    "Lex #165",
    "Lex #71",
    "Lex #191",
    "Lex #10",
    "Lex #98",
    "Lex #228",
    "Lex #100",
    "Lex #66",
    "Lex #222",
    "Lex #40",
    "Lex #141",
    "Lex #62",
    "Lex #220",
    "Lex #93",
    "Lex #109",
    "Lex #89",
    "Lex #36",
    "Lex #21",
    "Lex #227",
    "Lex #12",
    "Lex #76",
    "Lex #192",
    "Lex #209",
    "Lex #26",
    "Lex #16",
    "Lex #193",
    "Lex #101",
    "Lex #147",
    "Lex #137",
    "Lex #37",
    "Lex #77",
    "Lex #30",
    "Lex #15",
    "Lex #212",
    "Lex #81",
    "Lex #90",
    "Lex #34",
    "Lex #32",
    "Lex #211",
    "Lex #63",
    "Lex #1",
    "Lex #145",
    "Lex #223",
    "Lex #180",
    "Lex #190",
    "Lex #86",
    "Lex #18",
    "Lex #133",
    "Lex #47",
    "Lex #43",
    "Lex #236",
    "Lex #199",
    "Lex #94",
    "Lex #113",
    "Lex #2",
    "Lex #118",
    "Lex #7",
    "Lex #235",
    "Lex #203",
    "Lex #153",
    "Lex #149",
    "Lex #167",
    "Lex #136",
    "Lex #102",
    "Lex #97",
    "Lex #50",
    "Lex #183",
    "Lex #112",
    "Lex #242",
    "Lex #150",
    "Lex #84",
    "Lex #234",
    "Lex #5",
    "Lex #115",
    "Lex #181",
    "Lex #69",
    "Lex #157",
    "Lex #174",
    "Lex #138",
    "Lex #162",
    "Lex #198",
    "Lex #139",
    "Lex #53",
    "Lex #59",
    "Lex #233",
    "Lex #124",
    "Lex #205",
    "Lex #120",
    "Lex #168",
    "Lex #92",
    "Lex #230",
    "Lex #176",
    "Lex #35",
    "Lex #11",
    "Lex #131",
    "Lex #151",
    "Lex #163",
    "Lex #25",
    "Lex #170",
    "Lex #216",
    "Lex #240",
    "Lex #129",
    "Lex #52",
    "Lex #95",
    "Lex #243",
    "Lex #189",
    "Lex #54",
    "Lex #106",
    "Lex #229",
    "Lex #127",
    "Lex #200",
    "Lex #114",
    "Lex #6",
    "Lex #61",
    "Lex #88",
    "Lex #159",
    "Lex #217",
    "Lex #140",
    "Lex #126",
    "Lex #48",
    "Lex #22",
    "Lex #105",
    "Lex #49",
    "Lex #38",
    "Lex #125",
    "Lex #135",
    "Lex #148",
    "Lex #132"
]

KNOWN_NAME = [
    "Lex Summers",
    "Lextricity",
    "BIG Lex",
    "Storm Lexer",
    "Lex Torched",
    "GamLex",
    "Victor Von Lex",
    "Captain Lex",
    "Miami Vinyl Lex",
    "He-Lex",
    "Lex Montana #3",
    "Beyond Lex",
    "Raphael Lex",
    "Zard Lex",
    "Pink Lexer",
    "\"Let's put a smile on Lex\"",
    "Boba Lex",
    "Bit Lex",
    "Lex the Fresh Prince",
    "Cobra Lex",
    "Beetle Lex",
    "Lex Games",
    "DeadLex",
    "Armor Red Lexer",
    "Zorro Lex",
    "Pilgrim Lex",
    "Leonardo Lex",
    "SubLex",
    "Santa Lex",
    "Inspector Lex",
    "Mutated Lex #3",
    "Symbiote Lex",
    "High Blood Lex",
    "Pac Lex",
    "Brak Lex",
    "ScarLexy",
    "Lex Attack",
    "ThanLexo",
    "Dad Lex",
    "Super Lex",
    "Lex Hefner",
    "Shrek Lex",
    "Lex and Jerry",
    "Charlie Lex",
    "Money Dive Lex",
    "Mutated Lex #4",
    "Volt Lex",
    "Lex the Manhunter",
    "Lex Ketchum",
    "McLex",
    "Mutated Lex #1",
    "Lex Trumper",
    "Smoker Lex",
    "Dali Lex",
    "CrickLex",
    "Killa Lex",
    "Yosemite Lex",
    "Lord Lex",
    "AkumLex",
    "Maul Lex",
    "Dummy Lex #1",
    "Bart Lex",
    "Spartan Lex",
    "Robo Lex",
    "Miami Lex",
    "Saiyan Lex",
    "Riddle me Lex",
    "Pickle Lex",
    "BendLex",
    "Holy Lex",
    "Kobe Lex #8",
    "Jurassic Lex",
    "MagLex",
    "Just Bekaws Lex #3",
    "Mojo Lexo",
    "Kobe Lex #24",
    "Incredible Lex",
    "Pirate Lex",
    "The One",
    "Bored out of my mind Lex",
    "Pharo Lex",
    "Attack on Lex",
    "Skeletor Lex",
    "Pop Lex",
    "Cult Leader Lex",
    "COVID Lex",
    "Hello Lexy",
    "Lex as Lex",
    "Kena Lex #2",
    "YoLex",
    "Muerto Lex",
    "D.A.R.E Lex",
    "Green GobLex",
    "White Lexer",
    "Money Lex",
    "Mario Lex",
    "Burglar Lex",
    "Wario Lex",
    "Reaper Lex",
    "One Lex",
    "Cat Lexy",
    "Blue Lexer",
    "Cyclops Lex",
    "Lex Montana #2",
    "Wakanda Lex",
    "Lex the Red Rhino",
    "BlankLex",
    "Karate Lex",
    "Just Bekaws Lex #2",
    "Army Lex",
    "Lex the Rhino",
    "\"Lex is a Joke\"",
    "Dummy Lex #2",
    "Space Ghost Lex",
    "Original Doc Lex",
    "Priest Lex",
    "KermLex",
    "Judge Lex",
    "Ram Lex",
    "Yellow Lexer",
    "Mega Lex #1",
    "Tailgate Lex",
    "Swat Lex",
    "Mutated Lex #2",
    "Marty McLex",
    "Punk Lex",
    "Lex be Loki",
    "Saur Lex",
    "FrankeinLex",
    "Lex the Punisher",
    "LL Cool Lex",
    "Lex's Laboratory",
    "BatLex",
    "Lex Allen",
    "Raider Lex",
    "Lexmo",
    "The Lex Thing",
    "Iron Lex",
    "Cell Lex",
    "Doodle Lex",
    "Pika Lex",
    "Lex Tracy ",
    "Spawn Lex",
    "Turbo Lex",
    "Beanie Lex",
    "Lex the Rat",
    "Easter Lex",
    "Ultra Lex",
    "Mummy Lex",
    "Graduation Lex",
    "Stan Lex",
    "PicaLex",
    "Lexy the Cat",
    "Lex Voorhees",
    "What's up Lex",
    "Kena Lex #1",
    "Iron Lex",
    "Clone Lex",
    "Scarlet Spider Lex",
    "WolverLex",
    "ChupaLex",
    "Invader Lex",
    "OG Lex",
    "Hey Lex",
    "Skater Lex",
    "Speed Lexer",
    "PhanLex",
    "Scrooge Lex",
    "Invasion Lex",
    "Mask Lex",
    "VenLex",
    "Movie Doc Lex",
    "Ye Lex",
    "Linked Lex",
    "Hawk Lex",
    "Lex Smash",
    "Casa de Lex",
    "Green Lexer",
    "Dia de los Lex",
    "Lex the Martian",
    "Bebop Lex",
    "PinoccLex",
    "Buzz Lex Year",
    "Gone Fishing Lex",
    "Kyle Lex",
    "Just Bekaws Lex #1",
    "Lex Vision",
    "Zombie Lex",
    "Beaster Lex",
    "Year of the Lex",
    "Jaws Lex",
    "Champion Lex",
    "Robin Lex",
    "Lex Stone #2",
    "Satan Lex",
    "Scorpion Lex",
    "Adventure Lex",
    "Hell's Kitchen Lex",
    "Banana Lex",
    "Fire Lex",
    "\"They Killed the Lex Bastard\"",
    "Planet Lex",
    "Dummy Lex #3",
    "CartLex",
    "Chuck Lex",
    "Michelangelo Lex",
    "Lex Stone #1",
    "Black Lexer",
    "Marlins Lex",
    "Red Lexer",
    "Lexinator",
    "ErniLex",
    "Clingy Lex",
    "Only Lex",
    "Spider Lex",
    "Nightmare on Lex Street",
    "Lex Lantern",
    "Minion Lex",
    "Fish Bowl Lex",
    "Krusty Lex",
    "Cobra Lex",
    "Lex Marino",
    "MF Lex",
    "Mega Lex #2",
    "Devilcat Lex",
    "Hawk Lexy",
    "Mr. Lex Rogers",
    "WoodLex",
    "GarLex",
    "Lex Montana #1",
    "Blast Lex",
    "NaruLex #2",
    "ChapuLex",
    "Red Lex Smash",
    "Referee Lex",
    "Donatello Lex",
    "WolverLex Vintage",
    "Rasta Lex",
    "Floaty Lex",
    "Adam Lex",
    "NaruLex #1",
    "Carnem Lex",
    "Gundam Lex",
    "Beach Lex",
    "CarnLex",
    "GoLex",
    "Donald Lex",
    "FriezLex",
    "Bum Lex",
    "Night Lex"
]

if __name__ == "__main__":
    generate_unknown_metadata()
    generate_known_metadata()
    generate_misc_metadata()
